export const REQUEST_ALERT = "APP/REQUEST_ALERT";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";

export const FETCH_USER = "USER/FETCH_USER";
export const AUTH_USER = "USER/AUTH";
export const REQUEST_USER = "USER/REQUEST";

export const FETCH_CLOTHES_SEARCH_PANEL_INFO = "CLOTHES/FETCH_CLOTHES_SEARCH_PANEL_INFO";
export const REQUEST_CLOTHES_SEARCH_PANEL_INFO = "CLOTHES/REQUEST_CLOTHES_SEARCH_PANEL_INFO";
export const REQUEST_SEARCH_CLOTHES = "CLOTHES/REQUEST_SEARCH_CLOTHES";
export const FETCH_SEARCH_CLOTHES = "CLOTHES/FETCH_SEARCH_CLOTHES";
export const ADD_FILTER = "CLOTHES/ADD_FILTER";
export const REMOVE_FILTER = "CLOTHES/REMOVE_FILTER";

export const REQUEST_PHOTOS_NAMES = "PHOTOS/REQUEST_PHOTOS_NAMES";
export const FETCH_PHOTOS_NAMES = "PHOTOS/FETCH_PHOTOS_NAMES";
