export const REQUEST_ALERT = "APP/REQUEST_ALERT";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";

export const REQUEST_AUTH = "USER/REQUEST_AUTH";
export const REQUEST_AUTH_AND_FETCH_USER = "USER/REQUEST_AUTH_AND_FETCH_USER";
export const AUTH_USER = "USER/AUTH_USER";
export const SET_USER_ROLE = "USER/SET_USER_ROLE";
export const REQUEST_USER_BY_EMAIL = "USER/REQUEST_USER_BY_EMAIL";
export const FETCH_USER = "USER/FETCH_USER";
export const REQUEST_REGISTRATION_USER = "USER/REQUEST_REGISTRATION_USER";
export const REQUEST_UPDATE_USER = "USER/REQUEST_UPDATE_USER";

export const REQUEST_CLOTHES_SEARCH_PANEL_INFO = "CLOTHES/REQUEST_CLOTHES_SEARCH_PANEL_INFO";
export const FETCH_CLOTHES_SEARCH_PANEL_INFO = "CLOTHES/FETCH_CLOTHES_SEARCH_PANEL_INFO";
export const REQUEST_SEARCH_CLOTHES = "CLOTHES/REQUEST_SEARCH_CLOTHES";
export const FETCH_CLOTHES = "CLOTHES/FETCH_CLOTHES";
export const ADD_FILTER = "CLOTHES/ADD_FILTER";
export const REMOVE_FILTER = "CLOTHES/REMOVE_FILTER";
export const REQUEST_CLOTHES_BY_SELLER_ID = "CLOTHES/REQUEST_CLOTHES_BY_SELLER_ID";
export const REQUEST_UPDATE_CLOTHES = "CLOTHES/REQUEST_UPDATE_CLOTHES";
export const UPDATE_CLOTHES = "CLOTHES/UPDATE_CLOTHES";
export const REQUEST_UPDATE_CLOTHES_DETAILS = "CLOTHES/REQUEST_UPDATE_CLOTHES_DETAILS";
export const UPDATE_CLOTHES_DETAILS = "CLOTHES/UPDATE_CLOTHES_DETAILS";
export const REQUEST_DELETE_CLOTHES = "CLOTHES/REQUEST_DELETE_CLOTHES";
export const DELETE_CLOTHES = "CLOTHES/DELETE_CLOTHES";
export const REQUEST_DELETE_CLOTHES_DETAILS = "CLOTHES/REQUEST_UPDATE_CLOTHES_DETAILS";
export const DELETE_CLOTHES_DETAILS = "CLOTHES/DELETE_CLOTHES_DETAILS";

export const ADD_PRODUCT_DETAILS = "PRODUCT/ADD_PRODUCT_DETAILS";
export const ADD_PRODUCT_DETAILS_ID = "PRODUCT/ADD_PRODUCT_DETAILS_ID";
export const ADD_PRODUCT = "PRODUCT/ADD_PRODUCT";
export const ADD_PRODUCT_PHOTOS = "PRODUCT/ADD_PRODUCT_PHOTOS";
export const REQUEST_SAVE_PRODUCT = "PRODUCT/REQUEST_SAVE_PRODUCT";

export const REQUEST_PHOTOS_NAMES = "PHOTOS/REQUEST_PHOTOS_NAMES";
export const FETCH_PHOTOS_NAMES = "PHOTOS/FETCH_PHOTOS_NAMES";
export const REQUEST_DELETE_PHOTO = "PHOTOS/REQUEST_DELETE_PHOTO";
export const DELETE_PHOTO = "PHOTOS/DELETE_PHOTO";
export const REQUEST_UPLOAD_PHOTO = "PHOTOS/REQUEST_UPLOAD_PHOTO";
export const CLEAR_PHOTO_STORE = "PHOTOS/CLEAR_PHOTO_STORE";

export const REQUEST_SAVE_CART = "CART/REQUEST_SAVE_CART";
export const SAVE_CART = "CART/SAVE_CART";
export const REQUEST_CART = "CART/REQUEST_CART";
export const FETCH_CART = "CART/FETCH_CART";
export const REQUEST_DELETE_CART = "CART/REQUEST_DELETE_CART";
export const DELETE_CART = "CART/DELETE_CART";
export const REQUEST_UPDATE_CART = "CART/REQUEST_UPDATE_CART";
export const UPDATE_CART = "CART/UPDATE_CART";
export const SELECT_ITEM = "CART/SELECT_ITEM";