export const REQUEST_ALERT = "APP/REQUEST_ALERT";
export const SHOW_ALERT = "APP/SHOW_ALERT";
export const HIDE_ALERT = "APP/HIDE_ALERT";

export const FETCH_USER = "USER/FETCH_USER";
export const AUTH_USER = "USER/AUTH";
export const REQUEST_USER = "USER/REQUEST";

export const FETCH_CLOTHES_SEARCH_PANEL_INFO = "CLOTHES/FETCH_CLOTHES_SEARCH_PANEL_INFO";
export const REQUEST_FETCH_CLOTHES_SEARCH_PANEL_INFO = "CLOTHES/REQUEST_FETCH_CLOTHES_SEARCH_PANEL_INFO";